pluginManagement {
    repositories {
        maven { url = "https://mirrors.cloud.tencent.com/nexus/repository/maven-public/" }
        maven { url = "https://maven.aliyun.com/repository/public/" }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = "https://mirrors.cloud.tencent.com/nexus/repository/maven-public/" }
        maven { url = "https://maven.aliyun.com/repository/public/" }
        google()
        mavenCentral()
        maven { url = "https://jitpack.io" }
    }
}

rootProject.name = "KeydroidXFocus"
include ':app'

includeBuild('../keydroidx-core') {
    dependencySubstitution {
        substitute module('io.github.cctyl.nokia:nokia-key-core') using project(':nokia-key-core')
        substitute module('io.github.cctyl.nokia:nokia-common') using project(':nokia-common')
        substitute module('io.github.cctyl.nokia:nokia-mini-shizuku') using project(':nokia-mini-shizuku')
    }
}
